// segment definicija

%{
    // proizvoljan C++ kod
    #include <iostream>

    extern int yylex();

    int yyerror(const std::string &poruka) {
        std::cerr << poruka << std::endl;
        exit(EXIT_FAILURE);
    }
%}

%token BROJ

%left '+'
%left '*'

%%

// segment akcija

niz_izraza
    : niz_izraza izraz ';' {
        std::cout << $2 << std::endl;
    }
    | izraz ';' {
        std::cout << $1 << std::endl;
    }
    ;

izraz
    : izraz '+' izraz {
        $$ = $1 + $3;
    }
    | izraz '*' izraz {
        $$ = $1 * $3;
    }
    | '(' izraz ')' {
        $$ = $2;
    }
    | BROJ {
        $$ = $1;
    }
    ;

%%

// segment korisnickog koda
int main() {
    if (yyparse() == 0) {
        std::cout << "prihvaceno" << std::endl;
    }
    else {
        std::cout << "nije prihvaceno" << std::endl;
    }
    return 0;
}
