%{
    #include <iostream>
    #include <cstdlib>
    #include "sintaksno_stablo.hpp"

    extern int yylex();
    extern int yylex_destroy();

    void yyerror(const std::string &poruka) {
        std::cerr << poruka << std::endl;
        exit(EXIT_FAILURE);
    }

    ASTCvor *ast = nullptr;
%}

%union {
    double realan_broj;
    std::string *niska;
    ASTCvor *ast_cvor;
}

%type<ast_cvor> izraz naredba niz_naredbi

%token SIN COS
%token<niska> ID
%token<realan_broj> BROJ

%left '+'
%left '*'
%precedence '(' '['
%right '\''

%%

program
    : niz_naredbi {
        ast = $1;
    }
    ;

niz_naredbi
    : niz_naredbi naredba {
        NizNaredbiCvor *niz_naredbi = dynamic_cast<NizNaredbiCvor *>($1);
        niz_naredbi->dodaj_naredbu($2);
        $$ = niz_naredbi;
    }
    | naredba {
        NizNaredbiCvor *niz_naredbi = new NizNaredbiCvor();
        niz_naredbi->dodaj_naredbu($1);
        $$ = niz_naredbi;
    }
    ;

naredba
    : ID '=' izraz '\n' {
        $$ = new DodelaCvor(*$1, $3);
        delete $1;
    }
    | izraz '\n' {
        $$ = new IspisCvor($1);
    }
    | '\n' {
        $$ = new PrazanCvor();
    }
    ;

izraz
    : izraz '+' izraz {
        $$ = new SabiranjeCvor($1, $3);
    }
    | izraz '*' izraz {
        $$ = new MnozenjeCvor($1, $3);
    }
    | SIN '(' izraz ')' {
        $$ = new SinCvor($3);
    }
    | COS '(' izraz ')' {
        $$ = new CosCvor($3);
    }
    | izraz '\'' {
        $$ = new IzvodCvor($1);
    }
    | izraz '[' BROJ ']' {
        $$ = new VrednostCvor($1, $3);
    }
    | izraz '(' izraz ')' {
        $$ = new KompozicijaCvor($1, $3);
    }
    | BROJ {
        $$ = new KonstantaCvor($1);
    }
    | ID {
        $$ = new PromenljivaCvor(*$1);
        delete $1;
    }
    | 'x' {
        $$ = new IdentitetCvor();
    }
    ;


%%

int main() {
    if (yyparse() == 0) {
        std::cout << "prihvaceno" << std::endl;
    }

    std::cout << *ast << std::endl;

    TabelaSimbola tabela_simbola;
    ast->interpretiraj(tabela_simbola);
    delete ast;

    yylex_destroy();
    return 0;
}
